### PR TITLE
Keep register allocator from inserting instructions before stackmaps.

### PR DESCRIPTION
**Pull request by ptersilie**
One problem with stackmaps is that the register allocator often inserts instructions (typically spill reloads) inbetween a call and the stackmap instruction. This not only messes with the offset reported by the stackmap (which we previously fixed), but also changes the machine variables being tracked. In other words, applying the offset fix, means we return to the right location after deoptimisation, but doing so means the tracked variables don't match anymore. To fix this properly, we need to make sure that no other instructions may be inserted inbetween a call and the stackmap instruction.

### CODE REVIEW

**Comment by ltratt** [comment]
This looks good, but I think we should add an LLVM test that checks that a stackmap has been inserted where we expect it to be. I'm also mildly curious if it breaks any existing tests!

bors try

**Comment by vext01** [comment]
I was thinking about this.

On a couple of occasions I've wondered if we should add an 'asm' option
YKD_PRINT_IR.

We'd also need a way to dump the stackmap section out, so we can tie (with
langtester) the stackmap address to the instruction address.

It's quite a bit of work, so it should be another PR.

**Comment by ltratt** [comment]
Does LLVM not have any tests that assert where in the asm output the stackmap goes? After all, this is ykllvm, so I'm not sure the JIT aspect of stackmaps is relevant to this change, which would affect normal LLVM too right?

**Comment by ptersilie** [comment]
@vext01 may correct me on this, but I thought we don't run the normal LLVM test with our changes, and all our changes are guarded by different command line arguments.

I don't mind adding a test for this change though. Do we already add LLVM tests somewhere where this could go @vext01 ?

**Comment by ltratt** [comment]
This might be a good point, perhaps, to slightly rethink our LLVM testing strategy, even if we only do something somewhat minimal for now. At the very least I think our new changes need some sort of test (otherwise we'll probably break them when we next merge in upstream; and we'll not have tests that we can ever hope to contribute this upstream).

**Comment by vext01** [comment]
> Do we already add LLVM tests somewhere where this could go

There's a handful of tests in `llvm/include/llvm/Transforms/Yk`. You can either extend these or add your own `Yk` test dirs for other llvm components.

**Comment by vext01** [comment]
Oops, sorry those are not tests.

**Comment by vext01** [comment]
You can make a `Yk` dir under `llvm/test` and hook it into cmake.

**Comment by vext01** [comment]
So what's the status of this one?

**Comment by ptersilie** [comment]
Closed in favour of https://github.com/ykjit/ykllvm/pull/61 which is a more general solution.

**Pull request closed without merging**
