### PR TITLE
Make control point work "by pointer".

### PR DESCRIPTION
**Pull request by vext01**
Previously we'd pass the control point its live variables in a struct by value, and it would return a (potentially mutated) struct containing the new state.

Like this:

```
%new_vars = new_control_point(YkLocation *%loc, YkCtrlPontVars %vars)
```

This change makes it so that the struct is passed by pointer:

```
new_control_point(YkLocation *%loc, YkCtrlPontVars* %vars_ptr)
```

If the struct is mutated, it happens in-place. No new state is returned.

This is required so that we can pass opaque pointers to Rust forLaurie's proposed `transition_location()` rework.

### CODE REVIEW

**Comment by vext01** [comment]
Companion PR coming soon.

**Comment by ptersilie** [comment]
This looked good by the way.

**Comment by ltratt** [comment]
Oops, I interpreted this one as for review by me since I asked for it. Mea culpa!

**Comment by vext01** [comment]
I'm a bit baffled.

It's a python failure:
```
  File "/home/buildbot-worker1/worker1/yk-buildbot-build-script-hw/build/llvm/utils/lit/lit/TestTimes.py", line 13, in read_test_times
    time, path = line.split(maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by vext01** [comment]
bors try

**Comment by ltratt** [comment]
Let's try again.

bors r+

**Pull request merged**
