### PR TITLE
Serialise switch instructions.

### PR DESCRIPTION
**Pull request by vext01**
Companion to https://github.com/ykjit/yk/pull/1123

### CODE REVIEW

**Comment by vext01** [comment]
Ready for re-review.

**Comment by vext01** [comment]
This one OK to squash too?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
OK to include a ykllvm update in the squash?

**Comment by ltratt** [comment]
Wrong PR :)

**Comment by vext01** [comment]
squashed.

**Comment by vext01** [comment]
CI failure fixed in d741b785d799

**Comment by vext01** [comment]
OK to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
squashed.

**Pull request merged**
