### PR TITLE
Update to LLVM 20230123

### PR DESCRIPTION
**Pull request by vext01**
Syncs us with LLVM main as of two days ago.

Companion PR coming.

### CODE REVIEW

**Comment by vext01** [comment]
Oh the merge commit message has the wrong date in the branch name. I changed the branch name late, but forgot the commit message. Does it matter? 2022 vs 2023 (classic mistake).

**Comment by ltratt** [comment]
Don't worry about it.

**Comment by ltratt** [comment]
Though bors doesn't seem to have kicked in?

**Comment by vext01** [comment]
bors ping

**Comment by ltratt** [comment]
Hmm, a job is running on b13, so I guess it's just not interacting with github properly. Let's see -- sometimes the second kick helps github pick things up (and doesn't cancel the job, at least sometimes!).

**Comment by vext01** [comment]
As discussed offline, we are going to have to do something else wrt formatting. Try this last commit.

[embarrassing how long it took to work out. `find -exec` doesn't do what I thought it does]

**Comment by ltratt** [comment]
Works for me. Please squash.

**Comment by vext01** [comment]
I think we will leave that last commit separate, so go ahead.

**Pull request merged**
