### PR TITLE
Added test to catch the additional live variable added by implicit.

### PR DESCRIPTION
**Pull request by nmdis1999**
This PR follows [PR#86](https://github.com/ykjit/ykllvm/pull/86) and implements a test which triggers thr runtime bug introduced by isImplicit() when compile yklua with unfixed ykllvm's version. We want to make sure that if changes to `FixStackmapsSpillReloads.cpp` triggers this bug again we can catch it with  this `ykllvm` test case.

The test case is generated by first preprocessing whole `yklua` into single `onelua.c` file and then using `cvise`. `cvise` is able to reduce the big c source file (around 25000 loc) to 43 loc `.c` file then is able to trigger the bug with unfixed ykllvm. 
Next, we generated `.ll` file (with ykllvm's  *debug mode* llc) and and just use the stackmap module part  as a test case under `ykllvm/llvm/test/CodeGen/X86`.

### CODE REVIEW

**Comment by nmdis1999** [comment]
@ltratt this PR is ready for review.

**Comment by vext01** [comment]
Is it worth documenting the reduction process in our docs (in a separate PR)? Or is it all pretty obvious?

I can see myself needing to use this tooling in the future.

**Comment by ltratt** [comment]
IMHO, it's pretty obvious, and we'd just end up duplicating cvise's documentation.

**Pull request merged**
