### PR TITLE
Make safepoint id a u64 rather than an Operand.

### PR DESCRIPTION
**Pull request by ptersilie**
Small QOL improvement. See yk PR: https://github.com/ykjit/yk/pull/1371

### CODE REVIEW

**Comment by ltratt** [comment]
There are some entertainingly unnecessary brackets in the `if` condition, but they were there originally, so don't need changing here. LGTM overall.

**Comment by vext01** [comment]
First commit needs rebasing away?

**Comment by ltratt** [comment]
@ptersilie I think you can rebase this against master now as the first and second commits are unrelated. Please force push.

**Comment by ptersilie** [comment]
Rebased.

**Pull request merged**
