### PR TITLE
Replace argument operands with instructions.

### PR DESCRIPTION
**Pull request by ptersilie**
Remove argument operands from the AOT IR by replacing them with instructions that we insert into the first block.

Taking the following LLVM IR as an example:
```
func main($1) {
  bb0:
    $2 = add $1, 0
}
```

Previously, this would become in our AOT IR:

```
func main(%1) {
  bb0:
    $1 = add arg(0), 0
}
```

Now this would become:

```
func main(%1) {
  bb0:
    $1 = arg(0)
    $2 = add $1, 0
}
```

Essentially, this gets rid of all argument operands in our AOT IR which simplifies `trace_builder` and especially deopt, which now have one less operand kind to handle.

### CODE REVIEW

**Comment by ltratt** [comment]
I like this change.

**Comment by ltratt** [comment]
@vext01 OK with this?

**Comment by vext01** [comment]
Yes, this looks ok.

(I was questioning whether we need `ArgumentMap`, since we could just scan the parent function's arguments, but it may be a little slower)

**Comment by ptersilie** [comment]
Force pushed formatting. Good to go again.

**Pull request merged**
