### PR TITLE
Simplify the control point.

### PR DESCRIPTION
**Pull request by ptersilie**
Since we can no longer return naturally from the control point there's some things we can remove now that are no longer needed. See commits for details.

### CODE REVIEW

**Comment by ltratt** [comment]
I guess this should change tests in the yk repo?

**Comment by vext01** [comment]
As if by magic, a companion PR appears!

**Comment by vext01** [comment]
This part LGTM.

**Comment by ptersilie** [comment]
Ok to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by ptersilie** [comment]
Squashed.

**Pull request merged**
