### PR TITLE
Serialise alloca properly.

### PR DESCRIPTION
**Pull request by vext01**
`llvm::AllocaInst` doesn't record the allocated type into its operand list, so a generic serialisation misses that info.

### CODE REVIEW

**Comment by ltratt** [comment]
> llvm::AllocaInst doesn't record the allocated type into its operand list, so a generic serialisation misses that info.

So what does this PR do?

**Comment by ltratt** [comment]
Yes, please force push an updated commit message.

**Comment by vext01** [comment]
done. 

If it's good, i'll add a commit to the yk side to get this new commit.

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
Just one commit :)

**Comment by ltratt** [comment]
Oh yeah, I asked you to force push -- mea culpa!

bors r+

**Pull request merged**
