### PR TITLE
Fix multiple locations in stackmaps

### PR DESCRIPTION
**Pull request by ptersilie**
When fixing a bug in our control point pass (which split blocks at the wrong instruction) this shook out another bug in stackmaps. So far we were only able to store one additional location per register. However, there can be cases were we need to store 2 additional locations. We get away with this fix for now but may have to revisit this in the future if even more locations are needed and implement a more general approach.

### CODE REVIEW

**Comment by ltratt** [comment]
Are we able to get a test in for this one?

**Comment by ptersilie** [comment]
The test is `bf.c` in yk, which failed after the control point fix. With these changes it's not failing anymore. The control point fix has a new assert so doesn't need a test. The bug I'm not sure how to test in ykllvm since it only manifests during deoptimisation.

**Comment by ptersilie** [comment]
Added an LLVM test for this (which is a slighly reduced LLVM IR version of the `bf.c` test). The test checks that this change indeed uses typically unused space in the stackmap to encode two additional locations of a live variable (e.g. another register and/or on the stack).

**Comment by ptersilie** [comment]
Ok to squash?

**Comment by ltratt** [comment]
Please squash.

**Comment by ptersilie** [comment]
Squashed.

**Comment by ptersilie** [comment]
Sorry about that. Ok to squash?

**Comment by ptersilie** [comment]
Squashed.

**Pull request merged**
